name: Runs E2E Tests
description: Runs E2E tests using chainsaw
inputs:
  k8s-version:
    description: Kubernetes version
    required: true
  kind-config:
    description: Kind cluster config
    default: ./scripts/config/kind/default.yaml
  kyverno-configs:
    description: Kyverno configs
    default: standard
  token:
    description: GH token
    required: true
  chainsaw-config:
    description: Chainsaw config
    default: ../../../.chainsaw.yaml
  tests-path:
    description: Tests path
    default: '.'
  chainsaw-tests:
    description: Test regex
    default: ''
  shard-index:
    description: Shard index
    default: '0'
  shard-count:
    description: Shard count
    default: '0'
runs:
  using: composite
  steps:
    # install tools
    - name: Install helm
      id: helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
    - name: Install Cosign
      uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
    - name: Install chainsaw
      uses: kyverno/action-install-chainsaw@f2b47b97dc889c12702113753d713f01ec268de5 # v0.2.12
      with:
        verify: true
    # create cluster
    - name: Create kind cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 #v0.20.0
      with:
        version: v0.27.0
        node_image: kindest/node:${{ inputs.k8s-version }}
        cluster_name: kind
        config: ${{ inputs.kind-config }}
    # deploy kyverno
    - name: Download kyverno images archive
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: kyverno.tar
    - name: Load kyverno images archive in kind cluster
      shell: bash
      run: |
        set -e
        kind load image-archive kyverno.tar --name kind
    - name: Install kyverno
      shell: bash
      run: |
        set -e
        export HELM=${{ steps.helm.outputs.helm-path }}
        export USE_CONFIG=${{ inputs.kyverno-configs }}
        make kind-install-kyverno
    - name: Wait for kyverno ready
      uses: ./.github/actions/kyverno-wait-ready
    # install kubectl-evict plugin needed for testing eviction subresource trigger
    - name: Install kubectl-evict
      shell: bash
      run: |
        set -e
        GOBIN=$(go env GOPATH)/bin
        go install github.com/ueokande/kubectl-evict@latest
        echo 'Adding kubectl-evict directory to PATH...'
        echo "${GOBIN}" >> "${GITHUB_PATH}"
    # run tests
    - name: Test with Chainsaw
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        set -e
        cd ./test/conformance/chainsaw
        chainsaw test ${{ inputs.tests-path }} \
          --config ${{ inputs.chainsaw-config }} \
          --include-test-regex '^chainsaw$/${{ inputs.chainsaw-tests }}' \
          --shard-index ${{ inputs.shard-index }} \
          --shard-count ${{ inputs.shard-count }}
    # debug
    - name: Debug failure
      if: failure()
      uses: ./.github/actions/kyverno-logs